module.exports = {
  up: queryInterface => queryInterface.bulkInsert('Replies',
    [
      {
        id: '1',
        reply: 'Weird parts',
        likes: 30,
        reviewId: '3',
        userId: '2',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '2',
        reply: 'Good doctor',
        likes: 10,
        reviewId: '1',
        userId: '2',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '3',
        reply: 'Getting things in order',
        likes: 16,
        reviewId: '1',
        userId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '4',
        reply: 'Order of things',
        likes: 105,
        reviewId: '4',
        userId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '5',
        reply: 'Order of things',
        likes: 105,
        reviewId: '4',
        userId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '6',
        reply: 'Order of things',
        likes: 105,
        reviewId: '4',
        userId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '7',
        reply: 'Order of things',
        likes: 105,
        reviewId: '4',
        userId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '8',
        reply: 'Order of things',
        likes: 105,
        reviewId: '4',
        userId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '9',
        reply: 'agnista lohan',
        likes: 105,
        reviewId: '3',
        userId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {}),
  down: queryInterface => queryInterface
    .bulkDelete('Replies', new Date('2050-12-12'), {})
};
