module.exports = {
  up: queryInterface => queryInterface.bulkInsert('Reviews',
    [
      {
        id: '1',
        review: 'Weird parts',
        rating: 2.5,
        likes: 30,
        bookId: '3',
        userId: '2',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '2',
        review: 'Good doctor',
        rating: 4,
        likes: 10,
        bookId: '1',
        userId: '2',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '3',
        review: 'Getting things in order',
        rating: 4,
        likes: 16,
        bookId: '1',
        userId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '4',
        review: 'Order of things',
        rating: 2.0,
        likes: 105,
        bookId: '4',
        userId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '5',
        review: 'Order of things',
        rating: 2.0,
        likes: 105,
        bookId: '4',
        userId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '6',
        review: 'Order of things',
        rating: 2.0,
        likes: 105,
        bookId: '4',
        userId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '7',
        review: 'Order of things',
        rating: 2.0,
        likes: 105,
        bookId: '4',
        userId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '8',
        review: 'Order of things',
        rating: 2.0,
        likes: 105,
        bookId: '4',
        userId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '9',
        review: 'agnista lohan',
        rating: 2.0,
        likes: 105,
        bookId: '3',
        userId: '1',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {}),
  down: queryInterface => queryInterface
    .bulkDelete('Reviews', new Date('2050-12-12'), {})
};
